data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
fusion:
  args: []
  core_method: v2_intermediate_fusion
loss:
  args:
    cls_weight: 1.0
    reg: 2.0
  core_method: point_pillar_loss

model:
  args:
    DA_feature_head: 384
    DA_instance_head: 176
    DA_feature_weight: 0.1
    DA_instance_weight: 0.1
    grl_feature_weight: 0.1
    grl_instance_weight: 0.1
    anchor_number: 2
    backbone_fix: false
    base_bev_backbone:
      layer_nums:
      - 3
      - 5
      - 8
      layer_strides:
      - 2
      - 2
      - 2
      num_filters:
      - 64
      - 128
      - 256
      num_upsample_filter:
      - 128
      - 128
      - 128
      upsample_strides:
      - 1
      - 2
      - 4
    communication:
      with_comm: false
      gaussian_smooth:
        c_sigma: 1.0
        k_size: 5
      threshold: 0.01
      layer_nums:
      - 3
      - 5
      - 8
      layer_strides:
      - 1
      - 2
      - 2
      multi_scale: false
      num_filters:
      - 64
      - 128
      - 256
      num_upsample_filter:
      - 128
      - 128
      - 128
      upsample_strides:
      - 1
      - 2
      - 4
    compression: 32
    head_dim: 384
    lidar_range: &id001
    - -140.8
    - -38.4
    - -5
    - 140.8
    - 38.4
    - 3
    max_cav: 5
    pillar_vfe:
      num_filters:
      - 64
      use_absolute_xyz: true
      use_norm: true
      with_distance: false
    point_pillar_scatter:
      grid_size: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          wAIAAAAAAADIAAAAAAAAAAEAAAAAAAAA
      num_features: 64
    raa_fusion:
      layer_nums:
      - 3
      - 5
      layer_strides:
      - 2
      - 2
      num_filters:
      - 64
      - 128
      num_upsample_filter:
      - 128
      - 256
      upsample_strides:
      - 2
      - 4
    voxel_size: &id002
    - 0.4
    - 0.4
    - 8
  core_method: point_pillar_range_comm_fusion_da

name: point_pillar_range_comm_fusion_da
optimizer:
  args:
    eps: 1.0e-10
    weight_decay: 0.0001
  core_method: Adam
  lr: 0.001
postprocess:
  anchor_args:
    D: 1
    H: 192
    W: 704
    cav_lidar_range: *id001
    feature_stride: 2
    h: 1.56
    l: 3.9
    num: 2
    r:
    - 0
    - 90
    vd: 4
    vh: 0.4
    vw: 0.4
    w: 1.6
  core_method: V2VoxelPostprocessor
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.2

preprocess:
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: *id002
  cav_lidar_range: *id001
  core_method: V2SpVoxelPreprocessor

train_params:
  batch_size: 2
  epoches: &epoches 40
  eval_freq: 100
  max_cav: 5
  save_freq: 5
root_dir: 'opv2v_data_dumping/train' # the path of the source domain
root_dir_target: 'v2v4real/train' # the path of the target domain
validate_dir: 'v2v4real/test'
yaml_parser: load_point_pillar_params

lr_scheduler:
  core_method: cosineannealwarm
  epoches: 40
  lr_min: 2.0e-5
  warmup_epoches: 20
  warmup_lr: 0.0002

wild_setting:
  async: false
  async_mode: 'sim'
  async_overhead: 0
  loc_err: false
  seed: 25
  xyz_std: 0
  ryp_std: 0